export const categories = [
    "App Recommendations",
    "Artificial Intelligence",
    "Cloud Computing",
    "Cybersecurity Tips",
    "Digital Tools",
    "E-commerce Solutions",
    "Gadget Reviews",
    "Gaming Tips & Setup",
    "Hardware Upgrades",
    "Mobile Devices",
    "Networking Solutions",
    "Online Privacy",
    "Operating Systems",
    "Premium Content",
    "Productivity Hacks",
    "Programming Languages",
    "Social Media Management",
    "Software Tutorials",
    "Smart Home Devices",
    "Streaming Services",
    "Tech News & Trends",
    "Troubleshooting",
    "Web Development"
];